language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t chaoyangfan/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true chaoyangfan/docker-react npm run test
